[package]
name = "stegno"
version = "0.1.0"
authors = ["Avishay Zarad <zarad.avishay@gmail.com>"]
edition = "2018"

[dependencies]
num = "0.2.0"
rand = "0.6.5"
itertools = "0.8.0"
clap = "2.33.0"
simple-error = "0.1.13"